"""empty message

Revision ID: 949e99b0bf81
Revises: c85209b90f1a
Create Date: 2024-07-29 11:57:52.654060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949e99b0bf81'
down_revision = 'c85209b90f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailsend', sa.DateTime(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expirience', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('expirience')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('mailsend')

    # ### end Alembic commands ###
