"""empty message

Revision ID: c9db3d9cce27
Revises: dcf610c2ef6c
Create Date: 2024-06-09 14:01:47.506365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9db3d9cce27'
down_revision = 'dcf610c2ef6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('place',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('len',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('occupations',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('o_kind',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('docs',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('contacts',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=True)

    with op.batch_alter_table('refs', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refs', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('contacts',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=True)
        batch_op.alter_column('docs',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
        batch_op.alter_column('o_kind',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('occupations',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('len',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=True)
        batch_op.alter_column('place',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
