"""empty message

Revision ID: eb47a4a71ad8
Revises: 
Create Date: 2024-03-27 16:41:54.617495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb47a4a71ad8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('place',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('len',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('occupations',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('o_kind',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=40), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=30),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=40),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('settings',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=40),
               existing_nullable=True)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('settings',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(length=30),
               existing_nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('o_kind',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('occupations',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('len',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)
        batch_op.alter_column('place',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(length=40),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('place', sa.VARCHAR(length=40), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=40), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('len', sa.VARCHAR(length=100), nullable=True),
    sa.Column('occupations', sa.VARCHAR(length=100), nullable=True),
    sa.Column('o_kind', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sex', sa.INTEGER(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
